export const APP_CONSTANTS = {
  LOGIN_TITLE: 'Welcome Back',
  LOGIN_SUBTITLE: 'Sign in to your account',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'Enter your email',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  SIGN_IN_BUTTON: 'Sign In',
  GOOGLE_SIGN_IN: 'Sign in with Google',
  DIVIDER_TEXT: 'or',
  NO_ACCOUNT_TEXT: "Don't have an account?",
  SIGN_UP_LINK: 'Sign up',
  UNKNOWN_ERROR: 'An unknown error occurred',
  AUTH_ERROR_LOG: 'Auth error:',
} as const; 
